export const FETCH_SET_ASSEMBLY_FEATURES = "FETCH_SET_ASSEMBLY_FEATURES";
export const SET_ASSEMBLY_FEATURE = "SET_ASSEMBLY_FEATURE";
export const RESET_ASSEMBLY_FEATURES = "RESET_ASSEMBLY_FEATURES";

